<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="SkiaSharp" Version="4.152.1" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.152.1" />

		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="4.0.1" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\CouponSheetGenerator\CouponSheetGenerator.csproj" />
		<ProjectReference Include="..\..\src\CouponSheetGenerator.Desktop\CouponSheetGenerator.Desktop.csproj" />
	</ItemGroup>

</Project>
